document.addEventListener("DOMContentLoaded", async () => {
    let roomId = "default";
    let pid = "local-" + Math.floor(Math.random() * 10000);
    let zoomContextStr = "";

    // Fetch authentication context generated by Go backend in HTML
    const metaCtx = document.querySelector('meta[name="zoom-app-context"]');
    if (metaCtx && metaCtx.content) {
        zoomContextStr = metaCtx.content;
    }

    const btn = document.getElementById("vote-btn");
    const statusText = document.querySelector(".status-text");

    try {
        // Zoom Apps SDK Init (Safe capabilities only)
        if (typeof zoomSdk !== 'undefined') {
            const configResponse = await zoomSdk.config({
                popoutSize: { width: 480, height: 360 },
                capabilities: ['getMeetingContext']
            });
            console.log("Zoom SDK Configured:", configResponse);
        } else {
            console.warn("Warning: Not running in Zoom Client");
        }
    } catch (e) {
        console.warn("Zoom SDK config failed", e);
        // Only a warning. HTMX WebSocket fallback will still work!
    }

    // Setup HTTP Polling and Actions
    const appContainer = document.getElementById("app");
    const pollingWrapper = document.getElementById("polling-wrapper");

    const protocol = window.location.protocol;
    const host = window.location.host;

    const urlParams = new URLSearchParams(window.location.search);
    roomId = urlParams.get('roomId') || "test-room";
    pid = urlParams.get('pid') || pid;

    let pollingUrl = `${protocol}//${host}/api/state?roomId=${encodeURIComponent(roomId)}&pid=${encodeURIComponent(pid)}`;
    let voteUrl = `${protocol}//${host}/api/vote?roomId=${encodeURIComponent(roomId)}&pid=${encodeURIComponent(pid)}`;

    if (zoomContextStr) {
        pollingUrl += `&zoom_context=${encodeURIComponent(zoomContextStr)}`;
        voteUrl += `&zoom_context=${encodeURIComponent(zoomContextStr)}`;
    }

    // Configure HTMX Polling on the gauge container wrapper
    pollingWrapper.setAttribute("hx-get", pollingUrl);
    pollingWrapper.setAttribute("hx-trigger", "every 2s");
    pollingWrapper.setAttribute("hx-swap", "innerHTML");

    // Configure HTMX POST on the vote button (Immediate UI Update)
    btn.setAttribute("hx-post", voteUrl);
    btn.setAttribute("hx-target", "#polling-wrapper");
    btn.setAttribute("hx-swap", "innerHTML");

    // HTMX Initialization Request - Make HTMX parse our new polling attributes
    htmx.process(appContainer);

    // Initial UI Setup
    btn.removeAttribute("disabled");
    statusText.innerHTML = "待機中 <span class='anonym-info'>(匿名)</span>";

    // Global Audio Setup for autoplay bypass
    window.hotaruAudio = new Audio('hotaru-piano.mp3');
    window.hotaruAudio.loop = true;

    // Handle audio autoplay policy workaround
    btn.addEventListener('click', () => {
        // Unlock with dummy play
        window.hotaruAudio.play().then(() => {
            window.hotaruAudio.pause();
            console.log("Audio unlocked successfully");
        }).catch(e => console.warn("Audio unlock failed:", e));
    });
});
