document.addEventListener("DOMContentLoaded", async () => {
    let roomId = "default";
    let pid = "local-" + Math.floor(Math.random() * 10000);
    let zoomContextStr = "";

    // Fetch authentication context generated by Go backend in HTML
    const metaCtx = document.querySelector('meta[name="zoom-app-context"]');
    if (metaCtx && metaCtx.content) {
        zoomContextStr = metaCtx.content;
    }

    const btn = document.getElementById("vote-btn");
    const statusText = document.querySelector(".status-text");

    try {
        // Zoom Apps SDK Init (Safe capabilities only)
        if (typeof zoomSdk !== 'undefined') {
            const configResponse = await zoomSdk.config({
                popoutSize: { width: 480, height: 360 },
                capabilities: ['getMeetingContext']
            });
            console.log("Zoom SDK Configured:", configResponse);
        } else {
            console.warn("Warning: Not running in Zoom Client");
        }
    } catch (e) {
        console.warn("Zoom SDK config failed", e);
        // Only a warning. HTMX WebSocket fallback will still work!
    }

    // Setup HTTP Polling and Actions
    const appContainer = document.getElementById("app");
    const gaugeContainer = document.getElementById("gauge-container");

    const protocol = window.location.protocol;
    const host = window.location.host;

    const urlParams = new URLSearchParams(window.location.search);
    roomId = urlParams.get('roomId') || "test-room";
    pid = urlParams.get('pid') || pid;

    let pollingUrl = `${protocol}//${host}/api/state?roomId=${encodeURIComponent(roomId)}&pid=${encodeURIComponent(pid)}`;
    let voteUrl = `${protocol}//${host}/api/vote?roomId=${encodeURIComponent(roomId)}&pid=${encodeURIComponent(pid)}`;

    if (zoomContextStr) {
        pollingUrl += `&zoom_context=${encodeURIComponent(zoomContextStr)}`;
        voteUrl += `&zoom_context=${encodeURIComponent(zoomContextStr)}`;
    }

    // Configure HTMX Polling on the gauge container
    gaugeContainer.setAttribute("hx-get", pollingUrl);
    gaugeContainer.setAttribute("hx-trigger", "every 2s");
    gaugeContainer.setAttribute("hx-swap", "outerHTML");

    // Configure HTMX POST on the vote button
    btn.setAttribute("hx-post", voteUrl);
    btn.setAttribute("hx-swap", "none");

    // HTMX Initialization Request - Make HTMX parse our new polling attributes
    htmx.process(appContainer);

    // Initial UI Setup
    btn.removeAttribute("disabled");
    statusText.innerHTML = "待機中 <span class='anonym-info'>(匿名)</span>";

    // Handle audio autoplay policy workaround
    // Audio context might be restricted. Ensure button click enables audio context.
    btn.addEventListener('click', () => {
        // By clicking the vote button, we satisfy the user interaction requirement for later Audio autoplay
        const audio = new Audio();
        audio.play().catch(() => { }).then(() => { audio.pause(); });
    });
});
