document.addEventListener("DOMContentLoaded", async () => {
    let roomId = "default";
    let pid = "local-" + Math.floor(Math.random() * 10000);
    let zoomContextStr = "";
    let hasError = false;

    // Fetch authentication context generated by Go backend in HTML
    const metaCtx = document.querySelector('meta[name="zoom-app-context"]');
    if (metaCtx && metaCtx.content) {
        zoomContextStr = metaCtx.content;
    }

    const btn = document.getElementById("vote-btn");
    const statusText = document.querySelector(".status-text");

    // Display error if missing on production
    if (!zoomContextStr && window.location.hostname !== "localhost") {
        document.querySelector(".status-text").innerHTML = "<span style='color:red'>エラー: 背景の認証データが見つかりません</span>";
        hasError = true;
    }

    try {
        // Zoom Apps SDK Init (Safe capabilities only)
        if (typeof zoomSdk !== 'undefined') {
            const configResponse = await zoomSdk.config({
                popoutSize: { width: 480, height: 360 },
                capabilities: ['getMeetingContext']
            });
            console.log("Zoom SDK Configured:", configResponse);
        } else {
            console.warn("Warning: Not running in Zoom Client");
        }
    } catch (e) {
        console.warn("Zoom SDK config failed", e);
        // Only a warning. HTMX WebSocket fallback will still work!
    }

    // Connect HTMX to WebSocket
    const appContainer = document.getElementById("app");

    // Dynamic wsUrl based on current window location
    const protocol = window.location.protocol === "https:" ? "wss:" : "ws:";
    const host = window.location.host;

    const urlParams = new URLSearchParams(window.location.search);
    roomId = urlParams.get('roomId') || "test-room";
    pid = urlParams.get('pid') || pid;

    let wsUrl = `${protocol}//${host}/ws?roomId=${encodeURIComponent(roomId)}&pid=${encodeURIComponent(pid)}`;
    if (zoomContextStr) {
        wsUrl += `&zoom_context=${encodeURIComponent(zoomContextStr)}`;
    }

    // Remove existing ht-ext/ws-connect if they exist (from HTML hardcoding)
    appContainer.removeAttribute("hx-ext");
    appContainer.removeAttribute("ws-connect");

    // Set them newly with the FULL url (including context)
    appContainer.setAttribute("hx-ext", "ws");
    appContainer.setAttribute("ws-connect", wsUrl);

    // HTMX Initialization Request - strictly AFTER the URL is built
    htmx.process(appContainer);

    // Initial UI Setup
    btn.removeAttribute("disabled");
    if (!hasError) {
        statusText.innerHTML = "待機中 <span class='anonym-info'>(匿名)</span>";
    }

    // Handle audio autoplay policy workaround
    // Audio context might be restricted. Ensure button click enables audio context.
    btn.addEventListener('click', () => {
        // By clicking the vote button, we satisfy the user interaction requirement for later Audio autoplay
        const audio = new Audio();
        audio.play().catch(() => { }).then(() => { audio.pause(); });
    });
});
